
server:
  port: 8381

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: ms-account
  datasource:
    url: jdbc:h2:mem:ms-account
    username: sa
    password: password
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

exceptions:
    account:
        not-found-message: "Conta não encontrada."
        not-found-description: "Não foi possível encontrar a conta corrente informada."
        without-balance-message: "Saldo insuficiente."
        without-balance-description: "Não foi possível efetuar o débito, o saldo da conta informada é insuficiente."